### PR TITLE
initial Vue project create

### PR DESCRIPTION
**Pull request by JLaveta**
Request to pull vue-setup branch into development. This branch contains the initial Vue.js project to be used for development of the web app moving forward. The demonstrated page can be found at: 

https://ad440storage.z4.web.core.windows.net/

No major modifications were made to the default Vue setup.

### CODE REVIEW

**Comment by gshields5541** [comment]
Okay. Are there any blobs setup or do I need to set the blobs up?

**Review by gshields5541 — COMMENTED** [review]
Okay, I think we should link this repository to the project I’ve set up.

**Comment by JLaveta** [comment]
I've created resources under the "ad440-app" resource group. I saw some resources created in the Azure account, but they weren't in the same resource group and they were setup in different locations.

Please use the ad440-app resource group for future work, and let's stick to the same location (currently set to West Central) for any other resources we may need.

**Comment by JLaveta** [comment]
The repository can be linked to whatever we decide on - however, the "ad440-app" resource group is where I've setup the TravisCI Pipeline.

**Comment by gshields5541** [comment]
Working with Microsoft Visual code and Following some steps to Build a Serverless web app : https://docs.microsoft.com/en-us/labs/build2018/serverlesswebapp/?tutorial-step=3  Total Time: 3 hours

**Comment by JLaveta** [comment]
@gshields5541 Can you please open a separate issue for your comment? 

This issue was opened specifically for pulling the vue-setup branch into development, and it looks like you're talking about something different. You are tagged on this issue because I requested your approval on the pull request.

**Comment by JLaveta** [comment]
@gshields5541 I'm going to go ahead and close this PR without merging. I have a new branch that includes TravisCI config that I'd like to bring in instead. I'll tag you on it shortly.

**Comment by gshields5541** [comment]
Okay, no problem

**Pull request closed without merging**
