### PR TITLE
Travis ci test

### PR DESCRIPTION
**Pull request by JLaveta**
@gshields5541 Request to merge TravisCI setup into development. The pipeline has been tested and is functioning as expected.

### CODE REVIEW

**Review by gshields5541 — APPROVED** [review]
It looks good to me. However, I trying to find out what code I need to post to? Is it the repository or azure account?

**Comment by JLaveta** [comment]
@gshields5541 Any changes to the web app need to be made through this repository. TravisCI will deploy anything brought into the development branch.

I would recommend you clone the repository locally, create a new branch, make your changes and test them locally, push them to a new branch (not development), and finally put in a pull request to merge into development. 

Be sure to open new issues in the project as you work on things and document your work so we're both on the same page with what is being done.

**Comment by gshields5541** [comment]
I've tried that, but I'm having some problems with sending a commit to a branch I've setup (draganddroptest). The branch isn't even being created on GitHub. Time: 3 hours.

**Comment by gshields5541** [comment]
Also, I'm getting a "permission denied" while committing to a branch I've created. Do I have authorization?

**Comment by JLaveta** [comment]
The only branch I've protected is master, so you should be able to push.
Can you send me a screenshot of your console? The commands you're using,
the output, etc.

**Comment by gshields5541** [comment]
I don’t see how that would matter since I can’t create a branch on the project page either.

**Comment by gshields5541** [comment]
There’s only one contributor listed on the project page and that’s you.

Gerald

**Comment by JLaveta** [comment]
Branches are created locally and then pushed to the repo as a new branch.

https://www.freecodecamp.org/forum/t/push-a-new-local-branch-to-a-remote-git-repository-and-track-it-too/13222

Hope this helps!

**Comment by gshields5541** [comment]
This won’t work due to me not being a contributor or a collaborator. I don’t even have commit access. Please go into the project settings, select collaborators, search by either username, full name or email address and make me and tody collaborators.

**Comment by JLaveta** [comment]
Ah, gotcha. I thought by having you added as part of the team you would
have access, but I was wrong. Thanks for spelling that out for me!

**Comment by JLaveta** [comment]
I added you as a collaborator on all three repos.

**Comment by gshields5541** [comment]
No biggie. I’m just glad to get the code committed. I was getting some warnings, but it’s working with the “fake upload service” code I’ve setup. I still have to figure out the code to send to the blob(s), But it at least something that was done to show we are progressing.

Gerald.

**Pull request merged**
